---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

mina:
  validator:
    source_url: http://packages.o1test.net
    ports:
      client_port: 8301
      external_port: 8302
      rest_port: 3085
      graphql_port: 3095
      metrics_port: 36455
