---
# maintains versions and can overwrite all.yml
mina:
  validator:
    version: 3.0.4-alpha1-889607b-focal-devnet
    config_file_name: config_889607b9.json
    peer_list_url: https://bootnodes.minaprotocol.com/networks/devnet.txt
    uptime_url: https://uptime-backend.minaprotocol.com/v1/submit
