---
# maintains versions and can overwrite all.yml
mina:
  validator:
    version: mina-devnet=3.0.4-alpha1-889607b
    release_type: alpha
    peer_list_url: https://bootnodes.minaprotocol.com/networks/devnet.txt
    uptime_url: https://uptime-backend.minaprotocol.com/v1/submit
