---
- name: Install Docker
  ansible.builtin.import_tasks: install_docker.yml

- name: Extract Binary
  ansible.builtin.import_tasks: extract_binary.yml
  # when: env != 'mesa'

# - name: Extract Mesa Binary
#   ansible.builtin.import_tasks: extract_mesa_binaries.yml
#   when: env == 'mesa'
