---
- name: Fetch mesa secrets environment from HCP Vault
  block:
    - name: Fetch private key from HCP Vault
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ env }}/{{ node_private_key_file_name }}"
        secret_destination_path: "{{ node_private_key_file_path }}"
        secret_type: json

    - name: Fetch libp2p key from HCP Vault
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ env }}/{{ node_libp2p_key_file_name }}"
        secret_destination_path: "{{ node_libp2p_key_file_path }}"
        secret_type: json

    - name: Fetch secrets environment from HCP Vault
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ env }}/{{ node_environment_secrets_file_name }}"
        secret_destination_path: "{{ node_environment_secrets_file_path }}"
        secret_type: environment
