---
- name: Find mina repository files
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "mina*.sources"
  register: mina_files

- name: Remove mina repository files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ mina_files.files }}"
  when: mina_files.matched > 0 

- name: Add mina protocol repository
  ansible.builtin.deb822_repository:
    name: "mina-{{ mina.validator.release_type }}"
    types: deb
    uris: "{{ mina.validator.source_url }}"
    suites: "{{ ansible_distribution_release }}"
    components: "{{ mina.validator.release_type }}"
    state: present
    enabled: true
    trusted: yes

- name: Install mina binary
  ansible.builtin.apt:
    name: "{{ mina.validator.version }}"
    state: present
    update_cache: true
  notify: 
    - Restart service

- name: Create symlink for binary
  ansible.builtin.file:
    src: "/usr/local/bin/mina"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    state: link
