---
# - name: Include the UFW rules vars file
#   ansible.builtin.include_vars:
#     file: vars/ufw_rules.yml

# - name: Apply UFW rules
#   ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
#   loop: "{{ node_ufw_rules }}"

# - name: Include user creation task
#   ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
#   vars:
#     home: "{{ node_home_dir }}"
#     directories: "{{ node_directories }}"
#     log_file_path: "{{ node_log_file_path }}"

- name: Include extract binary task
  ansible.builtin.include_tasks: extract_binary.yml

# - name: Fetch secrets from HCP Vault and save
#   when: fetch_validator_keys | default(false) | bool
#   block:
#     - name: Fetch private key from HCP Vault
#       ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
#       vars:
#         vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_priavte_key_file_name }}"
#         secret_destination_path: "{{ node_private_key_path }}"
#         secret_type: json

#     - name: Fetch public key from HCP Vault
#       ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
#       vars:
#         vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_public_key_file_name }}"
#         secret_destination_path: "{{ node_public_key_path }}"
#         secret_type: key

#     - name: Fetch secrets environment from HCP Vault
#       ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
#       vars:
#         vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_environment_secrets_file_name }}"
#         secret_destination_path: "{{ node_environment_secrets_file_path }}"
#         secret_type: environment

# - name: Copy mina config
#   ansible.builtin.copy:
#     src: "{{ env }}/config.json"
#     dest: "{{ node_config_file_path }}"
#     owner: "{{ service_identifier }}"
#     group: "{{ service_identifier }}"
#     mode: "0644"

# - name: Copy mina env file
#   ansible.builtin.template:
#     src: "{{ env }}/general.env.j2"
#     dest: "{{ node_environment_general_file_path }}"
#     owner: root
#     group: root
#     mode: "0644"

# - name: Copy mina node systemd service file
#   ansible.builtin.template:
#     src: "{{ env }}/systemd.service.j2"
#     dest: /etc/systemd/system/{{ service_identifier }}.service
#     owner: root
#     group: root
#     mode: "0644"
#   notify:
#     - Reload service
#     - Restart service
